data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.icdar_2015
        class: ICDAR2015
        ICDAR2015:
          dirnames:
            - '''../dataset/incidental_scene_text_2015/test/'''
          imsize: 736
          mean: '(0.485, 0.456, 0.406)'
          std: '(0.229, 0.224, 0.225)'
          shrink_ratio: 0.5
          max_shrink: 20
          ignore_blur_text: True
          image_extents: ['''.jpg''', '''.png''', '''.jpeg''', '''.JPG''', '''.PNG''', '''.JPEG''']
          label_extent: '''.json'''
      batch_size: 4
      shuffle: False
      pin_memory: True
      num_workers: 12
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.PAN_net
  class: PANNet
  PANNet:
    backbone_name: '''resnet34'''
    backbone_pretrained: False
    num_FPEMs: 2
    shrink_ratio: 0.5
    score_threshold: 0.5
    area_threshold: 0.

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      hmean:
        module: flame.handlers.metrics.evals.metric
        class: HMean
        HMean:
          output_transform: 'lambda x: (x[0], x[1], x[2], x[3])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/incidental_scene_text_2015/2112141659/best_model_147_pan_loss=-0.3366.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.predictor
  class: Predictor
  Predictor:
    evaluator_name: '''engine'''
    imsize: 736
    output_dir: '''checkpoint/incidental_scene_text_2015/2112141659/best_model_147_pan_loss=-0.3366/test/'''
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.tester
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
