DB:
  module: modules.word_detection.db_pytorch.detector
  class: WordDetector
  WordDetector:
    model:
      module: models.definitions.db_pytorch.db
      class: DBModel
      DBModel:
        backbone_name: '''resnet50'''
        config_backbone: 
          pretrained: False
          in_channels: 3
        config_head:
          in_channels: 256
        config_neck:
          in_channels: [256, 512, 1024, 2048]
          inner_channels: 256
    
    min_size: 3
    weight_path: '''models/weights/db/ic15_resnet50'''
    batch_size: 2
    imsize: 1028
    device: '''cpu'''
    mean: (0.485, 0.456, 0.406)
    std: (0.229, 0.224, 0.225)